# -*- coding: utf-8 -*-
"""Import the DOA "70% chemical + 30% organic" fruit tables into crop_fertilizer_plan.

Source: E:\\DOA_Soil\\3.ขัอมูลคำแนะนำการให้ปุ๋ยไม้ผล 70_ ปุ๋ยอินทรีย์ 30_ _.xlsx
Layout (normal table, one row per soil combo):
  col A ลำดับ | B OM% | C P | D K | E N | F P2O5 | G K2O
  then 4 stages, each 4 cols: 46-0-0, 18-46-0, 0-0-60, ปุ๋ยอินทรีย์
    stage start cols: 8, 12, 16, 20 ; stage name from row3 + row4 (merged)
Output: supabase/migrations/009_import_fertilizer_plan_70.sql  (use_type='organic70')
"""
import openpyxl, os, re, sys
sys.stdout.reconfigure(encoding="utf-8")

SRC = os.path.join(r"E:\DOA_Soil", "3.ขัอมูลคำแนะนำการให้ปุ๋ยไม้ผล 70_ ปุ๋ยอินทรีย์ 30_ _.xlsx")
OUT = r"D:\doa_test_kit\supabase\migrations\009_import_fertilizer_plan_70.sql"

STAGE_COLS = [8, 12, 16, 20]  # 1-indexed start col of each stage (4 cols each)

# แก้ชื่อ sheet -> ชื่อพืชในฐานข้อมูล
def crop_from_sheet(sheet):
    name = re.sub(r"70%.*", "", sheet).strip()
    return {"สัปปะรด": "สับปะรด"}.get(name, name)

def norm(v):
    return "" if v is None else str(v).strip()

def clean(s):
    return re.sub(r"\s+", " ", norm(s)).strip()

def parse_range(s):
    s = norm(s).replace(" ", "")
    if not s or s == "-":
        return (None, None)
    m = re.match(r"^<([\d.]+)$", s)
    if m: return (None, float(m.group(1)))
    m = re.match(r"^>([\d.]+)$", s)
    if m: return (float(m.group(1)), None)
    m = re.match(r"^([\d.]+)-([\d.]+)$", s)
    if m: return (float(m.group(1)), float(m.group(2)))
    raise ValueError(f"bad range {s!r}")

def sql_num(x):
    return "NULL" if x is None else (str(int(x)) if float(x).is_integer() else str(x))

def sql_str(s):
    return "'" + norm(s).replace("'", "''") + "'"

def parse_sheet(ws, crop):
    # stage name per start col = row3 + row4
    stage_names = {}
    for si, c in enumerate(STAGE_COLS, 1):
        top = clean(ws.cell(row=3, column=c).value)
        sub = clean(ws.cell(row=4, column=c).value)
        stage_names[c] = (f"{top} {sub}".strip(), si)
    out = []
    for r in range(7, ws.max_row + 1):
        a = ws.cell(row=r, column=1).value
        if not isinstance(a, (int, float)):
            continue
        om = parse_range(ws.cell(row=r, column=2).value)
        p  = parse_range(ws.cell(row=r, column=3).value)
        k  = parse_range(ws.cell(row=r, column=4).value)
        for c in STAGE_COLS:
            stage, order = stage_names[c]
            for off in range(4):
                grade = clean(ws.cell(row=5, column=c + off).value)
                if not grade:
                    continue
                val = ws.cell(row=r, column=c + off).value
                if not isinstance(val, (int, float)) or val == 0:
                    continue  # 0 = ไม่ใช้สูตรนี้ในระยะนั้น
                is_org = "อินทรีย์" in grade
                out.append((crop, "organic70", om[0], om[1], p[0], p[1], k[0], k[1],
                            stage, order, grade, float(val),
                            "กก./ต้น" if is_org else "กรัม/ต้น"))
    return out

def main():
    wb = openpyxl.load_workbook(SRC, data_only=True)
    all_rows, summary = [], []
    for sheet in wb.sheetnames:
        crop = crop_from_sheet(sheet)
        rows = parse_sheet(wb[sheet], crop)
        all_rows.extend(rows)
        combos = len(set((x[2],x[3],x[4],x[5],x[6],x[7]) for x in rows))
        org = sum(1 for x in rows if x[10] and "อินทรีย์" in x[10])
        summary.append((crop, len(rows), combos, org))
    wb.close()

    with open(OUT, "w", encoding="utf-8") as f:
        f.write("-- 009_import_fertilizer_plan_70.sql — auto-generated by scripts/import_fertilizer_plan_70.py\n")
        f.write("-- ตารางปุ๋ย 70% เคมี + 30% อินทรีย์ (ไม้ผล 9 ชนิด) -> use_type='organic70'\n\n")
        f.write("-- เพิ่มค่า 'organic70' ให้ constraint use_type\n")
        f.write("alter table public.crop_fertilizer_plan drop constraint if exists crop_fertilizer_plan_use_type_check;\n")
        f.write("alter table public.crop_fertilizer_plan add constraint crop_fertilizer_plan_use_type_check\n")
        f.write("  check (use_type in ('straight', 'compound', 'organic70'));\n\n")
        f.write("delete from public.crop_fertilizer_plan where use_type = 'organic70';\n\n")
        f.write("insert into public.crop_fertilizer_plan\n")
        f.write("  (crop_id, use_type, om_min, om_max, p_min, p_max, k_min, k_max, stage, stage_order, grade, amount, unit)\n")
        f.write("select c.id, v.use_type, v.om_min, v.om_max, v.p_min, v.p_max, v.k_min, v.k_max, v.stage, v.stage_order, v.grade, v.amount, v.unit\n")
        f.write("from (values\n")
        lines = []
        for idx, x in enumerate(all_rows):
            crop, ut, om0, om1, p0, p1, k0, k1, stage, order, grade, amount, unit = x
            cast = "::numeric" if idx == 0 else ""
            lines.append(
                f"({sql_str(crop)}, {sql_str(ut)}, "
                f"{sql_num(om0)}{cast}, {sql_num(om1)}{cast}, {sql_num(p0)}{cast}, {sql_num(p1)}{cast}, "
                f"{sql_num(k0)}{cast}, {sql_num(k1)}{cast}, {sql_str(stage)}, {order}, {sql_str(grade)}, "
                f"{sql_num(amount)}{cast}, {sql_str(unit)})")
        f.write(",\n".join(lines))
        f.write("\n) as v(crop_name, use_type, om_min, om_max, p_min, p_max, k_min, k_max, stage, stage_order, grade, amount, unit)\n")
        f.write("join public.crops c on c.name = v.crop_name;\n")

    print(f"WROTE {OUT}\nTOTAL rows: {len(all_rows)}\n")
    print(f"{'crop':<14}{'rows':>6}{'combos':>8}{'organic':>9}")
    for crop, n, combos, org in summary:
        print(f"{crop:<14}{n:>6}{combos:>8}{org:>9}")

if __name__ == "__main__":
    main()
